# Generated by Django 5.1.7 on 2025-10-17 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='ID de Pedido')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora del Pedido')),
                ('total_neto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Neto')),
                ('metodo_pago', models.CharField(max_length=50, verbose_name='Método de Pago')),
                ('estado_pedido', models.CharField(default='Pendiente', max_length=30, verbose_name='Estado del Pedido')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
