# Generated by Django 5.1.7 on 2025-10-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_hora',
            field=models.DateTimeField(verbose_name='Fecha y Hora del Pedido'),
        ),
    ]
